services:
  sqlserver-local:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: "sqlserver-local"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

