services:
  mysql-local:
    image: "mysql:8.0.44-debian"
    container_name: "mysql-local"
    environment:
      MYSQL_USER: "analyx-user"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
    expose:
      - "3306"
    ports:
      - "3306:3306"

