spring:
  application:
    name: analyx

  thymeleaf:
    cache: false
  datasource:
    url: "jdbc:mysql://localhost:3306/analyx"
    password: 123456
    username: root
    hikari:
      data-source-properties:
        allowPublicKeyRetrieval: true
  flyway:
    enabled: true
    validate-migration-naming: true