spring:
  application:
    name: analyx

  thymeleaf:
    cache: false
  datasource:
    url: "jdbc:mysql://localhost:3306/analyx"
    password: 123456
    username: root
    hikari:
      data-source-properties:
        allowPublicKeyRetrieval: true
  flyway:
    enabled: true
    validate-migration-naming: true
    url: "jdbc:mysql://localhost:3306/"
    password: "${spring.datasource.password}"
    user: "${spring.datasource.username}"
    schemas: flyway
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
server:
  error:
    include-binding-errors: always
    include-message: always